on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest

  test:
    runs-on: self-hosted
    permissions:
      contents: read
    needs: build-and-publish
    
    steps:
      - uses: actions/checkout@v2
        with:
          chromedriver-version: '114.0.5735.16' # İsteğe bağlı: Chrome sürümüne uyacak şekilde belirtmek için kullanılır
      - name: Start Xvfb and Chromedriver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # İsteğe bağlı: Ekrana gerek yoksa kullanılır
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Selenium tests
        run: python3 pythonlogintest.py

  deploy:
    needs: test
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Docker host
        run: |
          docker stop myapp || true
          docker rm myapp || true
          docker run -d -p 5000:5000 --name myapp ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
