name: Build and publish Docker image to GitHub Packages

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
 
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          
      
      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
          
      - name: Deploy to Docker host
        run: |
          try {
              docker stop myapp
          }
          catch {
              # Hata oluşursa devam et
          }
          try {
              docker rm myapp
          }
          catch {
              # Hata oluşursa devam et
          }
          docker run -d -p 5000:5000 --name myapp ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
          
      - name: Remove old Docker images
        run: |
          try {
               
              docker image rm fe5bfb3542cb59d51c958eaf3f5e1748ed22ac62a5a8e12a9ce24c7388c3e2a3
          }
          catch {
                 # Hata oluşursa devam et
               }
 

