on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          
      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
          
      - name: Run Selenium tests
        run: |
          docker run -e SE_EVENT_BUS_HOST=selenium-hub -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 --network host --rm -v $PWD:/usr/src/app -w /usr/src/app python:3 python pythonlogintest.py
   
      - name: Deploy to Docker host
        run: |
          docker stop myapp || true
          docker rm myapp || true
          docker run -d -p 5000:5000 --name myapp ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
          
