name: Build and publish Docker image to GitHub Packages

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: my-docker-image

jobs:
  build-and-publish:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and publish Docker image
        run: |
          sudo docker build -t ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest .
          sudo docker push ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Docker host
        run: |
          sudo docker stop myapp || true
          sudo docker rm myapp || true
          sudo docker run -d -p 5000:5000 --name myapp ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest

      - name: Remove old Docker images
        run: |
          sudo docker images --filter "reference=${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}" --format "{{.Repository}}:{{.Tag}}" | awk '!/:latest$/' | xargs -I {} sudo docker image rm -f {}
